src/pages/loggedInView.vue

Resolves or continues [AR-6192](https://team-1624093970686.atlassian.net/browse/AR-6192).
1. Implemented code to get Chain id (if passed) from Auth SDK and use that as default.
[AR-6192]: https://team-1624093970686.atlassian.net/browse/AR-6192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6192] chain selection through auth SDK

---

src/components/SendTransaction.vue
src/components/SignMessageCompact.vue

Resolves or continues [AR-6210](https://team-1624093970686.atlassian.net/browse/AR-6210).
1. Fixed issue that shows undefined when Switch chain using Wagmi-connector.
[AR-6210]: https://team-1624093970686.atlassian.net/browse/AR-6210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6210] rainbow connector issue

---

src/utils/onrampmoney.ramp.ts

Not ticketed.
None.
Added Avalanche C-Chain to the onramp.money blacklist.

Added Avalanche C-Chain to the blacklist

---

src/App.vue
src/components/ActivityView.vue
src/components/AssetsView.vue
src/components/ChainListModal.vue
src/components/SendTokensPreview.vue
src/components/SendTransaction.vue
src/components/SendTransactionCompact.vue
src/components/SignMessage.vue
src/components/SignMessageCompact.vue
src/components/VJsonViewer.vue
src/components/signMessageAdvancedInfo.vue
src/pages/ActivitiesScreen.vue
src/pages/RequestsScreen.vue
src/pages/loggedInView.vue
src/services/nft.service.ts
src/store/app.ts

Resolves [AR-6097](https://team-1624093970686.atlassian.net/browse/AR-6097).
- Updated activities
- Updated requests
[AR-6097]: https://team-1624093970686.atlassian.net/browse/AR-6097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6097] Redesign activities and request

---

src/App.vue

- Hide a way to collapse in widget mode

Hotfix for widget mode

---

package-lock.json
src/pages/backCompat/signIn.vue
src/pages/initPageV2.vue
src/pages/signInV2.vue
src/store/user.ts

Resolves or continues [AR-6206](https://team-1624093970686.atlassian.net/browse/AR-6206).
None.
See ticket and and the Auth SDK changes.
[AR-6206]: https://team-1624093970686.atlassian.net/browse/AR-6206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Wallet UI changes (direct token-based authentication)

---

src/App.vue
src/pages/loggedInView.vue

Resolves [AR-6271](https://team-1624093970686.atlassian.net/browse/AR-6271).
None.
See ticket, no UI changes necessary.
[AR-6271]: https://team-1624093970686.atlassian.net/browse/AR-6271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Don't set iframe styles for non-UI wallet modes

---

src/components/ActivityView.vue
src/pages/backCompat/initPage.vue
src/pages/backCompat/signIn.vue

- Fixed backward compatability for really old versions

[Fix] Dashboard fix

---

src/pages/backCompat/signIn.vue
src/pages/loginRedirect.vue
src/pages/signInV2.vue
src/utils/redirectUtils.ts

- Removed `console.log`
- Removed duplicate function

[Fix] Remove duplicate function, removed console.logs

---

src/utils/redirectUtils.ts

- Removing code added due to merge conflict

[Fix] Removing code added due to merge conflict

---

package.json
src/models/Connection.ts
src/pages/loggedInView.vue
src/utils/requestHandler.ts
src/utils/requestManagement.ts

- Remove multiple `connect` events

Fixing multiple emit of connect event

---

src/components/WalletHeader.vue

Hotfix
- Show app name on hover

Show app name on hover

---

src/App.vue

Grow wallet on hover

---

src/pages/MFASetup.vue

Remove share expired condition

Remove share expired condition

---

src/pages/MFASetup.vue

Remove share expiry

---

README.md

Resolves or continues [AR-6193](https://team-1624093970686.atlassian.net/browse/AR-6193).
NA
Readme cleanup and update Arcana Readme template
[AR-6193]: https://team-1624093970686.atlassian.net/browse/AR-6193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: #AR-6193 readme update

---

src/App.vue
src/components/SignMessageCompact.vue
src/components/signMessageAdvancedInfo.vue
src/utils/requestManagement.ts

- Added max height to wallet
- Show toast only if wallet is expanded

AR-6399 Error Toast is covering all of the wallet UI

---

package.json

[Fix] Update auth core version

---

package-lock.json
package.json
src/pages/MFARestoreScreen.vue
src/pages/backCompat/signIn.vue
src/pages/loginRedirect.vue
src/pages/signInV2.vue
src/utils/PasswordlessLoginHandler.ts
src/utils/redirectUtils.ts

- Update auth-core version
- Decoding of state params.

[Fix] Update auth-core and used base64 decoding for state params

---

src/pages/MFARestoreScreen.vue

- Fixed reading state from session instead of local in MFA restore

[FIx] MFA restore issue

---

src/pages/signInV2.vue

Supply key to userInfo

---

src/pages/signInV2.vue

- Add privateKey to userInfo after firebase login

[Mainnet Hotfix] Add key to userInfo

---

src/components/AssetsView.vue
src/models/Connection.ts
src/pages/AddTokenScreen.vue
src/pages/MFARequiredScreen.vue
src/pages/MFARestoreScreen.vue
src/pages/MFASetup.vue
src/pages/ReconnectV1.vue
src/pages/SendTokens.vue
src/pages/backCompat/initPage.vue
src/pages/backCompat/signIn.vue
src/pages/initPageV2.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue
src/services/nft.service.ts
src/store/user.ts
src/utils/redirectUtils.ts
src/utils/requestManagement.ts
src/utils/storage.ts
src/utils/storageWrapper.ts
src/utils/validateAndPopulateContractForToken.ts

- Added functions to update local and session storage with fallback to in memory
- Updated usages
- [] The branch name follows the format: `developer/AR-XXX-issue-name`.

[Feature] Storage wrapper update

---

package-lock.json
package.json
src/App.vue
src/components/AssetsView.vue
src/main.ts
src/models/Connection.ts
src/pages/AddTokenScreen.vue
src/pages/MFARequiredScreen.vue
src/pages/MFARestoreScreen.vue
src/pages/MFASetup.vue
src/pages/ReconnectV1.vue
src/pages/SendTokens.vue
src/pages/backCompat/initPage.vue
src/pages/backCompat/signIn.vue
src/pages/initPageV2.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue
src/routes/index.ts
src/services/nft.service.ts
src/store/user.ts
src/utils/getAuthProvider.ts
src/utils/redirectUtils.ts
src/utils/requestManagement.ts
src/utils/storage.ts
src/utils/storageWrapper.ts
src/utils/validateAndPopulateContractForToken.ts
vue.config.js

Resolves or continues [AR-6411](https://team-1624093970686.atlassian.net/browse/AR-6411).
None.
Please include a summary of the changes and any relevant context not covered in the issue ticket. You can assume that reviewers will begin by reading the description of the linked issue.
When making primarily visual changes, it's helpful to include before and after screenshots.
[AR-6411]: https://team-1624093970686.atlassian.net/browse/AR-6411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Session ID handling in the Wallet UI

---

package-lock.json
package.json
src/App.vue
src/components/AssetsView.vue
src/main.ts
src/models/Connection.ts
src/pages/AddTokenScreen.vue
src/pages/MFARequiredScreen.vue
src/pages/MFARestoreScreen.vue
src/pages/MFASetup.vue
src/pages/ReconnectV1.vue
src/pages/SendTokens.vue
src/pages/backCompat/initPage.vue
src/pages/backCompat/signIn.vue
src/pages/initPageV2.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue
src/routes/index.ts
src/services/nft.service.ts
src/store/user.ts
src/utils/PasswordlessLoginHandler.ts
src/utils/getAuthProvider.ts
src/utils/redirectUtils.ts
src/utils/requestManagement.ts
src/utils/storage.ts
src/utils/storageWrapper.ts
src/utils/validateAndPopulateContractForToken.ts
vue.config.js

[Feature] Reconnection

---

src/pages/MFARestoreScreen.vue
src/pages/initPageV2.vue
src/utils/storage.ts

- Removed setting on `loginSrc` when it is undefined
- Fixed fetch from session on mfaRestore page

[Fix] Fixed a bug of setting loginSrc on undefined value

---

src/pages/backCompat/signIn.vue
src/pages/loginRedirect.vue

- Added storing to sessionStorage post login for standalone apps purpose
- [] The branch name follows the format: `developer/AR-XXX-issue-name`.

[Fix] Readded storing to session post login for standalone apps

---

src/models/Connection.ts
src/pages/MFASetup.vue

- Fixed typo in mfaSetup page
- Added domain back to error

[Fix] MFA setup error

---

package.json

- Fixed `auth-core` to specific version

[Fix] Fixed auth-core version to non updating

---

src/components/GasPrice.vue
src/components/SendTransaction.vue
src/components/VJsonViewer.vue
src/components/signMessageAdvancedInfo.vue
src/services/gasPrice.service.ts
src/store/request.ts

hotfix eip 1559

---

src/components/GasPrice.vue
src/store/request.ts

Max fee per gas fix

---

src/components/SendTransaction.vue
src/store/request.ts

- Calculate maxFee before hexlify

Calculate gas fee

---

src/pages/MFARestoreScreen.vue
src/pages/ReconnectV1.vue
src/pages/loginRedirect.vue
src/utils/constants.ts
src/utils/redirectUtils.ts

- Used constant `SESSION_EXPIRY_MS` and reduced to 30 mins.
- Fixed sending back expiry from reconnect page

[Fix] Expiry in reconnect page

---

src/pages/loggedInView.vue
src/store/user.ts

Resolves or continues [AR-6504](https://team-1624093970686.atlassian.net/browse/AR-6504).
None.
Please include a summary of the changes and any relevant context not covered in the issue ticket. You can assume that reviewers will begin by reading the description of the linked issue.
When making primarily visual changes, it's helpful to include before and after screenshots.
[AR-6504]: https://team-1624093970686.atlassian.net/browse/AR-6504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Return LoginType from the wallet UI for use in the Auth SDK

---

package.json

- Update auth-core version to fix steam issue and revert global

[Fix] Updated auth-core version

---

src/pages/loggedInView.vue

- Changed connectToParent to async, waiting for promise to resolve before moving foward

[Fix] Added waiting for connection promise to resolve before moving forward

---

src/pages/initPageV2.vue

Fix init page error

---

src/components/WalletHeader.vue

- Use logo mark instead of horizontal logo

[Main] use logo mark instead of horizontal logo

---

src/components/VJsonViewer.vue
src/index.css

Add pre to VJsonViewer

---

src/pages/MFARestoreScreen.vue
src/pages/signInV2.vue

- Added storing of user info on restore flow
- Checking setSessionID exists before being called

[Fix] Added storing user info on mfa restore flow

---

src/pages/MFARestoreScreen.vue
src/pages/signInV2.vue

- Fix for storing user info on mfa restore

[Fix] Added storing user info on mfa restore flow (#408)

---

src/pages/MFARestoreScreen.vue
src/pages/signInV2.vue

- Update params to fetch gas limit

Update gas limit params

---

src/utils/requestManagement.ts

Return tx once tx is sent to blockchain, let the dapp do the polling if tx is success or not. Don't wait it in wallet

Return tx once tx is sent to blockchain

---

package.json

[Hotfix] Update auth-core version for api timeout

---

package-lock.json
package.json
src/components/GasPrice.vue
src/components/SendTransaction.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue
src/utils/requestManagement.ts

Reverts arcana-network/wallet-ui#426

Revert "Add logs to request to check what values are been passed, plus modify…"

---

src/components/ActivityView.vue
src/components/ChainListModal.vue
src/components/NFTView.vue
src/pages/ActivitiesScreen.vue
src/pages/AddOrEditNFTScreen.vue
src/pages/AddTokenScreen.vue
src/pages/NftDetailsScreen.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue
src/pages/loggedInView.vue
src/services/nft.service.ts
src/utils/accountHandler.ts
src/utils/requestManagement.ts
src/utils/validateAndPopulateContractForNft.ts

- Fix gas estimation for nft transfer and erc20 transfer from wallet
- Handle cases of switching chain from other pages
- Update styling of Activity page to show success and pending state

Fix nft transfer

---

src/pages/backCompat/signIn.vue
src/pages/loggedInView.vue
src/pages/signInV2.vue
src/utils/validators.ts

[Fix] Add disposable detect

---

package-lock.json
package.json
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/signInV2.vue
src/store/user.ts
src/utils/PasswordlessLoginHandler.ts
src/utils/getAuthProvider.ts
src/utils/redirectUtils.ts

- Added fetching jwt login post login

[Feature] Added jwt token fetch post login

---

src/store/app.ts

Fix height of compact mode

---

netlify/edge-functions/csp.js

[Fix] Fixed header string setting with bracket

---

src/components/AssetsView.vue
src/components/ChainListModal.vue
src/components/NFTView.vue
src/components/SignMessage.vue
src/components/SwitchEthereumChain.vue
src/components/WalletAddEthereumChain.vue
src/components/WalletHeader.vue
src/components/WalletSwitchEthereumChain.vue
src/components/WalletWatchAssetErc20.vue
src/components/WalletWatchAssetNFT.vue
src/models/Asset.ts
src/models/Connection.ts
src/services/chainlist.service.ts
src/store/rpc.ts
src/utils/accountHandler.ts
src/utils/requestManagement.ts
src/utils/validateAndPopulateContractForNft.ts

- Fixed switch chain signing message, show `chainName` in title if chain name is present in wallet
- Show appropriate UI for `wallet_addEthereumChain`, `wallet_switchEthereumChain` and `wallet_watchAsset` instead of showing raw data
https://github.com/arcana-network/wallet-ui/assets/24249988/365ebc98-ee43-4b2d-99b8-9fa4ec2268a4

Fix switch chain sign message and show approriate UI for wallet methods

---

src/utils/scw.ts

Resolves [AR-7026](https://team-1624093970686.atlassian.net/browse/AR-7026).
1. Added gateway URL as third argument.
[AR-7026]: https://team-1624093970686.atlassian.net/browse/AR-7026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

pass gateway URL init function

---

src/utils/constants.ts

Add usd tether for bsc

---

src/components/AssetsView.vue
src/models/Asset.ts
src/services/nft.service.ts
src/utils/constants.ts

- Update chainlist for autofetching nfts
- Add default assets for Eth, Polygon, Bsc and Arbitrum

Add default assets in wallet

---

src/components/AssetsView.vue

Get logo from logo url

---

src/utils/constants.ts

Update polygon icon

---

package-lock.json
package.json
src/utils/getAuthProvider.ts

Update auth core sdk to 1.0.0-beta.17

---

package-lock.json
package.json
src/components/AssetsView.vue
src/utils/constants.ts
src/utils/getAuthProvider.ts

Sync dev to testnet

---

package-lock.json
package.json

Resolves or continues [AR-7036](https://team-1624093970686.atlassian.net/browse/AR-7036).
1. Updated SCW to `0.0.18`.
[AR-7036]: https://team-1624093970686.atlassian.net/browse/AR-7036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update SCW version

---

package-lock.json
package.json

Resolves or continues [AR-7043(https://team-1624093970686.atlassian.net/browse/AR-7043).
1. Update SCW version to `0.0.18`.

update SCW version (#502)

---

package-lock.json
package.json

Resolves [AR-7053](https://team-1624093970686.atlassian.net/browse/AR-7053).
1. Updated SCW SDK `0.0.19`
[AR-7053]: https://team-1624093970686.atlassian.net/browse/AR-7053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update scw sdk to 0.0.19

---

src/services/getNFTDetails.service.ts
src/services/nft.service.ts
src/utils/nftUtils.ts

Remove check for token details

---

src/components/NFTView.vue

Handle fallback image for nft

---

src/components/NFTView.vue

Add bg to nft view

---

src/components/ActivityView.vue
src/components/NFTView.vue
src/components/SendNftPreview.vue
src/pages/AddOrEditNFTScreen.vue
src/pages/NftDetailsScreen.vue
src/services/getNFTDetails.service.ts
src/services/nft.service.ts
src/utils/nftUtils.ts
src/utils/validateAndPopulateContractForNft.ts

Handle empty nft token uri

---

src/pages/SendTokens.vue

1. if gas-less, don't estimate custom gas fee

[hotfix] custom gas fee estimate

---

src/pages/loggedInView.vue

Resolves [AR-7064](https://team-1624093970686.atlassian.net/browse/AR-7064).
1. Merge changes of #518 to testnet
[AR-7064]: https://team-1624093970686.atlassian.net/browse/AR-7064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

show loader till scw address fetched (#518)

---

src/components/ChainListModal.vue
src/pages/loggedInView.vue

1. Fix race condition where SCW address is fixed before updating rpc config in request handler.

[Fix] SCW address race condition issue

---

src/components/ChainListModal.vue
src/components/UserWallet.vue
src/pages/loggedInView.vue

Fix for SCW address issue

---

src/pages/SendTokens.vue
src/utils/accountHandler.ts

Resolves or continues [AR-7068](https://team-1624093970686.atlassian.net/browse/AR-7068).
1. Don't silence error when sending custom token.
[AR-7068]: https://team-1624093970686.atlassian.net/browse/AR-7068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7068] - Fix

---

src/pages/SendTokens.vue
src/utils/accountHandler.ts

Resolves [AR-7073](https://team-1624093970686.atlassian.net/browse/AR-7073)
1. Merge changes of [AR-7068](https://team-1624093970686.atlassian.net/browse/AR-7068)
[AR-7073]: https://team-1624093970686.atlassian.net/browse/AR-7073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AR-7068]: https://team-1624093970686.atlassian.net/browse/AR-7068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

merge change of AR-7068 to testnet

---

src/pages/loggedInView.vue

Fix wallet starter tips 

---

netlify/edge-functions/csp.js

Allow localhost usage in any port as frame ancestor

---

src/pages/loggedInView.vue

Resolves [AR-7155](https://team-1624093970686.atlassian.net/browse/AR-7155).
1. Move the logic to a specific function.
2. Call at last of `onMount` fn.
[AR-7155]: https://team-1624093970686.atlassian.net/browse/AR-7155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix]  AR-7155

---

package-lock.json
package.json
src/pages/MFARestoreScreen.vue
src/pages/MFASetup.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/signInV2.vue
src/utils/devLogger.ts
src/utils/getAuthProvider.ts
src/utils/solana/getPrivateKey.ts

Non evm solana add logs

---

netlify/edge-functions/csp.js
src/routes/index.ts

- Added csp for global-redirect allowance

[Fix] csp header for global redirect

---

netlify/edge-functions/csp.js
package-lock.json
package.json
src/models/Connection.ts
src/pages/loggedInView.vue
src/routes/index.ts
src/utils/evm/requestHandler.ts
src/utils/solana/requestHandler.ts

Resolves or continues [AR-7221](https://team-1624093970686.atlassian.net/browse/AR-7221).
1. implemented logic to set and get address type (eoa or scw).
[AR-7221]: https://team-1624093970686.atlassian.net/browse/AR-7221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7221] pass address type sdk

---

package-lock.json
package.json
src/components/AppFooter.vue
src/components/ExportKeyModal.vue
src/models/Connection.ts
src/pages/PermissionRequest.vue
src/pages/homeScreen.vue
src/pages/loggedInView.vue
src/pages/profileScreen.vue
src/utils/evm/requestHandler.ts
src/utils/solana/requestHandler.ts

1. Implemented logic to send key to auth-verify and then copy the key.

fix copy issue for new tab req pvt key

---

src/components/PermissionRequest/SendTransaction.vue

1. pass max fee to calculate gas price

[fix] gas price issue

---

src/components/PermissionRequest/SendTransaction.vue
src/components/SendTransaction.vue
src/pages/PermissionRequest.vue

1. Fix for incorrect gas price on send transaction in permission request page.

gas price issue

---

package-lock.json
package.json
src/pages/signInV2.vue
src/utils/getAuthProvider.ts

- Added functions to support otp login

[Feature] Added otp login support

---

src/pages/signInV2.vue

- Added field required for mfa in-wallet

[Fix] Added pk field required for mfa

---

src/pages/MFARestoreScreen.vue
src/pages/globalRedirect.vue
src/pages/loggedInView.vue
src/pages/signInV2.vue

[Fix] In-app mfa flow fix

---

src/pages/globalRedirect.vue

- Fix missing case insensitive check

[Fix] Fixed missing case insensitive comparison

---

src/pages/MFARequiredScreen.vue
src/pages/MFASetup.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue
src/utils/storage.ts

- Fix regression for MFA setup in in-app

[Fix] regression for setup in app

---

src/pages/PermissionRequest.vue

Resolves or continues [AR-7319](https://team-1624093970686.atlassian.net/browse/AR-7319).
1. Initialised SCW SDK in the new permission request tab
[AR-7319]: https://team-1624093970686.atlassian.net/browse/AR-7319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7319] - Karthik/scw sign issue

---

src/pages/PermissionRequest.vue
src/pages/SendTokens.vue

Resolves [AR-7278](https://team-1624093970686.atlassian.net/browse/AR-7278) and [AR-7327](https://team-1624093970686.atlassian.net/browse/AR-7327).
For - AR-7278
1. Added condition to check if transaction is gas-less, if so, then don't check balance
For - AR-7327
1. Set wallet address type by comparing with SCW address which is fetched from scw instance.
[AR-7278]: https://team-1624093970686.atlassian.net/browse/AR-7278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AR-7327]: https://team-1624093970686.atlassian.net/browse/AR-7327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AR-7278 and AR-7327

---

package.json

[Hotfix] Update auth-core

---

package.json

[Fix] Updated key helper version

---

package.json

[Fix] Updated auth version

---

src/App.vue
src/components/BuyTokens.vue
src/components/UserWallet.vue

- Remove on ramp money
- Move fetching code from App.vue to UserWallet component

Remove onramp money

---

src/pages/signInV2.vue
src/utils/getAuthProvider.ts

- Moved storing to local storage before redirecting

[Fix] Moved storing to ls before redirect to restore

---

src/pages/globalRedirect.vue

- Fix fetching token on global login

[Fix] Fetching loginToken on global login

---

src/pages/globalRedirect.vue
src/pages/signInV2.vue
src/utils/getAuthProvider.ts

- Added a fix for MFA restore during OTP login

MFA fix for OTP login

---

package-lock.json
package.json
src/pages/SendTokens.vue

**Changed the Error Handling in Case of Sending Tokens.**
- Created, Case 1: Inform of No Gas Fees for any Transaction when Balance is Zero
- Case 2: Inform when Balance Token < Token Selected for Transaction.
- Case 3: Misc

AR 7121 Fix: Error Handling in Case of Sending Tokens.

---

src/pages/SendTokens.vue

Feat: Max-Transfer-Button-Functionality
Added Max Button Functionality.
Added case to choose max balance for transfer, covered Input Error when Balance is Zero.

Feat: AR-7120-Max-Transfer-Button-Functionality

---

src/pages/SendTokens.vue

Resolves [AR-7573](https://team-1624093970686.atlassian.net/browse/AR-7573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Checklist
The changes have been tested locally.
[AR-7573]: https://team-1624093970686.atlassian.net/browse/AR-7573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Max Button and Transaction Error Merge ReDo

---

src/pages/StarterTips/index-page.vue
src/pages/StarterTips/page-1.vue
src/pages/StarterTips/page-2.vue
src/pages/StarterTips/page-3.vue
src/pages/StarterTips/page-4.vue
src/pages/StarterTips/page-5.vue
src/pages/StarterTips/page-6.vue

Resolves or continues [AR-7536](https://team-1624093970686.atlassian.net/browse/AR-7536).
1. Fixed stepper count issue
2. Add skip button
[AR-7536]: https://team-1624093970686.atlassian.net/browse/AR-7536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7536] wallet starter tips bug on main-net

---

src/pages/StarterTips/index-page.vue
src/pages/StarterTips/page-1.vue
src/pages/StarterTips/page-2.vue
src/pages/StarterTips/page-3.vue
src/pages/StarterTips/page-4.vue
src/pages/StarterTips/page-5.vue
src/pages/StarterTips/page-6.vue
src/pages/profileScreen.vue

Resolves or continues [AR-7536](https://team-1624093970686.atlassian.net/browse/AR-7536).
1. Added Skip button.
2. Fixed stepper counter
3. Fixed for light theme.
[AR-7536]: https://team-1624093970686.atlassian.net/browse/AR-7536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AR-7536 mainnet

---

src/components/SendTransaction.vue
src/components/WalletHeader.vue
src/pages/SendTokens.vue

- Fixed issue with chain dropdown button
- Fixed issue with gas estimation, if gas estimation fails, it will default to 21000

Fix chain button and fix gas estimation failure

---

src/store/activities.ts

Resolves or continues [AR-7316](https://team-1624093970686.atlassian.net/browse/AR-7316).
1. Implemented code to parse data and get sent amount.
[AR-7316]: https://team-1624093970686.atlassian.net/browse/AR-7316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7316] - dev

---

package-lock.json
package.json

Resolves or continues [AR-7656](https://team-1624093970686.atlassian.net/browse/AR-7656).
1. Updated SCW sdk to `0.0.30`
[AR-7656]: https://team-1624093970686.atlassian.net/browse/AR-7656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update scw sdk

---

src/components/SendNftPreview.vue
src/components/SendTokensPreview.vue
src/components/SendTransaction.vue
src/components/SendTransactionCompact.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue

Resolves or continues [AR-7502](...).
[AR-7502]: https://team-1624093970686.atlassian.net/browse/AR-7502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Design Feedbacks Implemented for Gasless Transactions

---

src/components/SendNftPreview.vue
src/components/SendTokensPreview.vue
src/components/SendTransaction.vue
src/components/SendTransactionCompact.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue

1. check chain type and wallet address type before getting paymaster balance.

hotfix paymaster check

---

package.json
src/components/ActivityView.vue
src/components/GasPriceMVX.vue
src/components/NFTView.vue
src/components/SendNftPreview.vue
src/components/SendTokensPreview.vue
src/components/SendTransaction.vue
src/components/SendTransactionCompact.vue
src/components/SignMessage.vue
src/models/Connection.ts
src/models/NFT.ts
src/pages/NftDetailsScreen.vue
src/pages/SendNft.vue
src/pages/SendTokens.vue
src/pages/initPageV2.vue
src/store/activities.ts
src/utils/content.ts
src/utils/multiversx/accountHandler.ts
src/utils/redirectUtils.ts

mvx changes merge to testnet

---

src/pages/backCompat/signIn.vue
src/pages/loggedInView.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue

[Hotfix] logout issue

---

src/pages/backCompat/signIn.vue
src/pages/loggedInView.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue

Reverts arcana-network/wallet-ui#635

Revert "[Hotfix] logout issue"

---

src/utils/scw.ts
vue.config.js

- Creating smaller chunks for vendor.

[Fix] chunking bundle

---

src/pages/loggedInView.vue
src/pages/signInV2.vue
src/utils/storage.ts

[Fix] caching walletMode call

---

src/App.vue
src/routes/index.ts

- Lazy load routes
- Lazy load some components like header and footer

[Fix] Added Lazy load

---

src/pages/backCompat/signIn.vue
src/pages/loggedInView.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue

[Fix] logout fn

---

src/pages/globalRedirect.vue
src/pages/loginRedirect.vue

- Capture exceptions on Sentry for failures at loginRedirect and globalRedirect

Add sentry logs

---

src/App.vue
src/pages/backCompat/signIn.vue
src/pages/globalRedirect.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/profileScreen.vue
src/pages/signInV2.vue
src/routes/index.ts
src/utils/scw.ts
src/utils/storage.ts
vue.config.js

- Added chunking
- Cached wallet mode call
- Lazy load routes
- Logout function
- Added sentry logs for login failures

Wallet improvements

---

src/components/UserWallet.vue
src/pages/MFARestoreScreen.vue
src/pages/globalRedirect.vue
src/pages/homeScreen.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/services/nft.service.ts
src/store/activities.ts
src/utils/PasswordlessLoginHandler.ts
src/utils/content.ts
src/utils/evm/accountHandler.ts
src/utils/redirectUtils.ts
src/utils/requestManagement.ts
src/utils/scw.ts
src/utils/storage.ts
src/utils/validateAndPopulateContractForNft.ts
src/utils/validateAndPopulateContractForToken.ts

Resolves or continues [AR-7833](https://team-1624093970686.atlassian.net/browse/AR-7833).
1. Added error codes to the errors in the file
2. Created new error entires,
[AR-7833]: https://team-1624093970686.atlassian.net/browse/AR-7833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7833] add error codes

---

src/pages/loggedInView.vue

Resolves or continues [AR-7885](https://team-1624093970686.atlassian.net/browse/AR-7885).
1. Set timeout before routing to login page
[AR-7885]: https://team-1624093970686.atlassian.net/browse/AR-7885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7885] Fix logout issue for dashboard

---

src/pages/SendTokens.vue

Resolves or continues [AR-7910](https://team-1624093970686.atlassian.net/browse/AR-7910).
1. Added `from` address to estimate gas.
2. got floor value before converting to hex string of gas fee.
[AR-7910]: https://team-1624093970686.atlassian.net/browse/AR-7910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7910] bitlayer issue

---

src/pages/SendTokens.vue

Resolves or continues [AR-7910](https://team-1624093970686.atlassian.net/browse/AR-7910).
Added from address to estimate gas.
got floor value before converting to hex string of gas fee.
[AR-7910]: https://team-1624093970686.atlassian.net/browse/AR-7910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ar 7910] testnet

---

src/pages/SendTokens.vue

Resolves or continues [AR-7910](https://team-1624093970686.atlassian.net/browse/AR-7910).
1. Added from address to estimate gas.
2. got floor value before converting to hex string of gas fee.
[AR-7910]: https://team-1624093970686.atlassian.net/browse/AR-7910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7910] Bitlayer trnx issue fix - mainnet

---

README.md

Resolves or continues [AR-6193](https://team-1624093970686.atlassian.net/browse/AR-6193).
NA
Removed contribution section in the readme file.
[AR-6193]: https://team-1624093970686.atlassian.net/browse/AR-6193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refs: #AR-6193 remove contribution section

---

src/pages/SendNft.vue
src/utils/content.ts

error codes fix

---

.github/workflows/manual-workflow-with-inputs.yml

- [AR-7989](https://team-1624093970686.atlassian.net/browse/AR-7989)
Initial changes
[AR-7989]: https://team-1624093970686.atlassian.net/browse/AR-7989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

deployment changes

---

src/components/AddNetwork.vue
src/components/EditNetwork.vue
src/utils/evm/accountHandler.ts
src/utils/evm/requestHandler.ts
src/utils/evm/rpcURLToProvider.ts
src/utils/getwalletType.ts
src/utils/requestManagement.ts

Resolves or continues [AR-8065](https://team-1624093970686.atlassian.net/browse/AR-8065).
None.
See ticket. No visual changes.
[AR-8065]: https://team-1624093970686.atlassian.net/browse/AR-8065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WebSocket RPC support

---

src/utils/evm/requestHandler.ts

Hotfix for WS RPC usage

---

deployments/ansible/deploy.yml

updated rsync file

---

src/utils/evm/accountHandler.ts
src/utils/evm/requestHandler.ts
src/utils/requestManagement.ts

Resolves or continues [AR-8095](https://team-1624093970686.atlassian.net/browse/AR-8095).
None.
[AR-8095]: https://team-1624093970686.atlassian.net/browse/AR-8095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WebSocket support fixes

---

src/pages/loggedInView.vue
src/pages/signInV2.vue
src/store/user.ts
src/utils/loginToken.ts

- Added user DID token for claim and signature

[Feat] Added user DID token

---

src/components/ChainListModal.vue
src/pages/loggedInView.vue
src/pages/signInV2.vue
src/store/user.ts
src/utils/loginToken.ts

[Feat] User DID token

---

src/utils/loginToken.ts

- Converting to hex before personal_sign for claims in user did token creation

[Fix] Added converting to hex before personal sign

---

src/utils/loginToken.ts

[Fix] Added converting to hex before personal sign (#704)

---

package-lock.json
package.json
src/utils/solana/splTokenRegistry.ts

Remove spl-token-registry
Fetch tokens using ajax from [CDN](https://cdn.jsdelivr.net/gh/solana-labs/token-list@main/src/tokens/solana.tokenlist.json) or [Github rawdata](https://raw.githubusercontent.com/solana-labs/token-list/main/src/tokens/solana.tokenlist.json)

Replace spl token registry

---

src/pages/loggedInView.vue
src/pages/profileScreen.vue
src/utils/evm/requestHandler.ts
src/utils/multiversx/requestHandler.ts
src/utils/near/requestHandler.ts
src/utils/solana/requestHandler.ts

- Fixed connectSent set to false on logout so connect event is sent on relogin

[Fix] Fixed setting connect sent to false on disconnect

---

src/components/SearchQuestion.vue
src/pages/MFASetup.vue

1. css fix input field for MFA screen

css fix input field

---

src/pages/MFARestoreScreen.vue
src/pages/globalRedirect.vue
src/pages/loginRedirect.vue
src/utils/loginToken.ts

- Fix login token for non evm logins.

[Fix] login token non evm

---

src/pages/MFARestoreScreen.vue
src/pages/globalRedirect.vue
src/pages/loggedInView.vue
src/pages/loginRedirect.vue
src/pages/profileScreen.vue
src/utils/evm/requestHandler.ts
src/utils/loginToken.ts
src/utils/multiversx/requestHandler.ts
src/utils/near/requestHandler.ts
src/utils/solana/requestHandler.ts

[Fix] login token for non evm & connectSent to false on disconnect
